---
- hosts: monitoring_elasticsearch
  gather_facts: false
  become: true
  collections:
    - onaio.monitoring
  pre_tasks:
    - name: load in monitoring vars
      include_vars:
        file: "vars/{{ monitoring_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: elastic.elasticsearch

    - role: onaio.monitoring.certbot
      when: es_use_certbot

    - role: onaio.monitoring.nginx
      when: es_use_nginx
