---
- hosts: monitoring_grafana
  gather_facts: false
  become: true
  collections:
    - onaio.monitoring
  pre_tasks:
    - name: load in monitoring vars
      include_vars:
        file: "vars/{{ monitoring_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
    - include_tasks: tasks/check-role.yml
      vars:
        monitoring_roles:
          - certbot
          - nginx
      with_items: "{{ monitoring_roles }}"
  roles:
    - role: cloudalchemy.grafana

    - role: onaio.monitoring.certbot
      when:  "{{ monitoring_use_certbot | default(true) }}"

    - role: onaio.monitoring.nginx

